apiVersion: apps/v1
kind: Deployment
metadata:
  name: jambonz-feature-server
  labels:
    app: jambonz-feature-server
spec:
  selector:
    matchLabels:
      app: jambonz-feature-server
  template:
    metadata:
      labels:
        app: jambonz-feature-server
    spec:
      initContainers:
        - args:
            - wait
            - --for=condition=complete
            - --timeout=300s
            - job/db-create
          image: d3fk/kubectl:v1.18
          name: db-create-wait
      containers:
        - name: drachtio
          image: drachtio/drachtio-server:k8s
          imagePullPolicy: Always
          args: ['drachtio', '--contact', 'sip:*:5060;transport=udp,tcp']
          env: 
        - name: freeswitch
          image: drachtio/drachtio-freeswitch-mrf:1.10.5
          volumeMounts:
            - mountPath: /tmp 
              name: temp-audio-volume
        - name: feature-server 
          image: jambonz/feature-server:latest 
          volumeMounts:
            - mountPath: /tmp 
              name: temp-audio-volume
          env:
            - name: HTTP_PORT
              value: "3000"
            - name: JAMBONES_FREESWITCH
              value: "localhost:8021:JambonzR0ck$"
            - name: JAMBONES_LOGLEVEL
              valueFrom:
                secretKeyRef:
                  name: jambonz
                  key: JAMBONES_LOGLEVEL
            - name: JAMBONES_CLUSTER_ID
              valueFrom:
                secretKeyRef:
                  name: jambonz
                  key: JAMBONES_CLUSTER_ID
            - name: DRACHTIO_HOST
              valueFrom:
                secretKeyRef:
                  name: jambonz
                  key: DRACHTIO_HOST
            - name: DRACHTIO_PORT
              valueFrom:
                secretKeyRef:
                  name: jambonz
                  key: DRACHTIO_PORT
            - name: DRACHTIO_SECRET
              valueFrom:
                secretKeyRef:
                  name: jambonz
                  key: DRACHTIO_SECRET
            - name: JAMBONES_MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: jambonz
                  key: JAMBONES_MYSQL_DATABASE
            - name: JAMBONES_MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: jambonz
                  key: JAMBONES_MYSQL_HOST
            - name: JAMBONES_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jambonz
                  key: JAMBONES_MYSQL_PASSWORD
            - name: JAMBONES_MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: jambonz
                  key: JAMBONES_MYSQL_USER
            - name: JAMBONES_REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: jambonz
                  key: JAMBONES_REDIS_HOST
            - name: JAMBONES_REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: jambonz
                  key: JAMBONES_REDIS_PORT
            - name: JAMBONES_TIME_SERIES_HOST
              valueFrom:
                secretKeyRef:
                  name: jambonz
                  key: JAMBONES_TIME_SERIES_HOST
            - name: ENABLE_METRICS
              valueFrom:
                secretKeyRef:
                  name: jambonz
                  key: ENABLE_METRICS
            - name: JAMBONES_NETWORK_CIDR
              valueFrom:
                secretKeyRef:
                  name: jambonz
                  key: JAMBONES_NETWORK_CIDR
            - name: JAMBONES_NETWORK_CIDR
              valueFrom:
                secretKeyRef:
                  name: jambonz
                  key: JAMBONES_NETWORK_CIDR
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jambonz
                  key: JWT_SECRET
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
      volumes:
      - name: temp-audio-volume
        emptyDir: {}
