apiVersion: apps/v1
kind: Deployment
metadata:
    name: traefik
spec:
    selector:
        matchLabels:
            app: traefik
    replicas: 1
    template:
        metadata:
            labels:
                app: traefik
        spec:
            serviceAccount: traefik
            containers:
            - name: traefik
              image: cognigydevelopment.azurecr.io/traefik:1.7.26-alpine_non_priviledged
              resources:
                requests:
                    memory: "70Mi"
                    cpu: "200m"
                limits:
                    memory: "200Mi"
                    cpu: "2000m"
              args: [
                "--api",
                "--kubernetes",
                "--entryPoints=Name:http Address::8000",
                "--metrics.prometheus=true"
              ]
              ports:
                - name: http
                  containerPort: 8000
                - name: metrics
                  containerPort: 8080
            imagePullSecrets:
            - name: cognigy-registry-token
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik

rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions, networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions, networking.k8s.io
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - traefik.containo.us
    resources:
      - middlewares
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - traefik.containo.us
    resources:
      - ingressroutes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - traefik.containo.us
    resources:
      - ingressroutetcps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - traefik.containo.us
    resources:
      - tlsoptions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - traefik.containo.us
    resources:
      - traefikservices
    verbs:
      - get
      - list
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik
subjects:
  - kind: ServiceAccount
    name: traefik
    namespace: jambonz
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: jambonz
  name: traefik