apiVersion: v1
kind: ConfigMap
metadata:
  name: jambonz-sbc-sip-conf
data:
  drachtio.conf.xml: |
    <drachtio>

        <!-- udp port to listen on for client connections and shared secret used to authenticate clients -->
        <admin port="9022" secret="cymru">0.0.0.0</admin>
        <request-handlers>
          <request-handler sip-method="INVITE">http://127.0.0.1:4000</request-handler>
        </request-handlers>
        <sip>
          <udp-mtu>4096</udp-mtu>
        </sip>

        <cdrs>false</cdrs>

        <logging>
            <sofia-loglevel>3</sofia-loglevel>
            <loglevel>debug</loglevel>
        </logging>

    </drachtio>