apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jambonz-sbc-rtp
  labels:
    app: jambonz-sbc-rtp
spec:
  serviceName: jambonz-sbc-rtp
  selector:
    matchLabels:
      app: jambonz-sbc-rtp
  template:
    metadata:
      labels:
        app: jambonz-sbc-rtp
    spec:
      containers:
        - name: rtpengine 
          image: jambonz/rtpengine:latest 
          args: ['rtpengine']
          env:
            - name: RTPENGINE_DTMF_LOG_PORT
              valueFrom:
                secretKeyRef:
                  name: jambonz
                  key: RTPENGINE_DTMF_LOG_PORT
          ports:
            - containerPort: 22222
      restartPolicy: Always
