apiVersion: v1
kind: Service
metadata:
  labels:
    app: jambonz-sbc-rtp
  name: jambonz-sbc-rtp
spec:
  ports:
    - name: "22222"
      port: 22222
      targetPort: 22222
      protocol: UDP
  selector:
    app: jambonz-sbc-rtp
