apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jambonz-sbc-rtp
  labels:
    app: jambonz-sbc-rtp
spec:
  selector:
    matchLabels:
      app: jambonz-sbc-rtp
  template:
    metadata:
      labels:
        app: jambonz-sbc-rtp
    spec:
      containers:
        - name: rtpengine 
          image: jambonz/rtpengine:latest 
          args: ['rtpengine']
          envFrom:
            - secretRef:
                name: jambonz
          ports:
            - containerPort: 22222
      restartPolicy: Always
